Repository viam-modules/viam-cartographer, pull requests merged in 2023-05, with the labels that each got.

#65 Update make install to remove binaries before copying new ones
  Makefile
Labels: safe to test

#68 RSDK-2938 Update Carto Probability Calculations
  viam-cartographer/src/io/submap_painter.cc
  viam-cartographer/src/io/submap_painter.h
  viam-cartographer/src/slam_service/slam_service.cc
  viam-cartographer/src/slam_service/slam_service.h
Labels: safe to test

#77 Fix Lint and Workflow Checkout of PR code
  .github/workflows/test.yml
  viam-cartographer/src/slam_service/slam_service.cc
Labels: appimage-ignore-tests, safe to test

#76 Further Workflow Fix
  .github/workflows/test.yml
  viam-cartographer/src/slam_service/slam_service.cc
Labels: safe to test

#80 [RSDK-2969] update appimage links to use the module
  .github/workflows/appimage-comment.yml
Labels: safe to test

#85 Add github workflow for creating rc0 appimages on rc0 tags
  .github/workflows/appimage.yml
  .github/workflows/main.yml
  Makefile
  etc/packaging/appimages/package_release_module.sh
  etc/packaging/appimages/utils.sh
Labels: appimage, safe to test

#84 Fix Readme for seamless setup & build process
  README.md
Labels: safe to test

#89 update-dependencies
  go.mod
  go.sum
Labels: safe to test

#83 [RSDK-2519] add version information
  Makefile
  module/main.go
Labels: safe to test

#94 Bump slam import
  go.mod
  go.sum
Labels: safe to test

#93 RSDK-3139 - add slam dependencies into cartographer
  config/config.go
  config/config_test.go
  config/setup.go
  config/setup_test.go
  dataprocess/dataprocess.go
  dataprocess/dataprocess_test.go
  go.mod
  go.sum
  integration_test.go
  internal/dim-2d/dim-2d.go
  internal/dim-2d/dim-2d_test.go
  internal/testhelper/testhelper.go
  sensors/lidar/lidar.go
  sensors/lidar/lidar_test.go
  sensors/utils/utils.go
  utils/utils.go
  utils/utils_test.go
  viam-cartographer.go
  viam-cartographer_test.go
Labels: safe to test

#95 RSDK-3135 - create modularization v2 enabled feature flag
  config/config.go
  config/config_test.go
  viam-cartographer.go
Labels: safe to test

#96 RSDK-3140 - validate depends on feature flag
  config/config.go
Labels: safe to test

#98 Reconcile slam repo changes
  config/config.go
  config/config_test.go
Labels: safe to test

#92 RSDK-2881: Update viam-cartographer to check if camera provides timestamps
  go.mod
  go.sum
  internal/dim-2d/dim-2d.go
Labels: safe to test

#69 RSDK-2890: Find OpenSSL correctly on MacOS
  .github/workflows/pullrequest-trusted.yml
  Makefile
  README.md
  viam-cartographer/scripts/build_viam_cartographer.sh
  viam-cartographer/scripts/setup_cartographer_macos.sh
Labels: safe to test

#101 point workflows back to main branch
  .github/workflows/pullrequest-trusted.yml
Labels: safe to test

#105 hotfix/RSDK-3358-carto-doesnt-boot-in-debug-mode
  module/main.go
Labels: safe to test
